
CREATE TABLE accounts (
 id SERIAL PRIMARY KEY,
 account_number VARCHAR(20) UNIQUE NOT NULL,
 type VARCHAR(20) NOT NULL,
 balance NUMERIC(18,2) NOT NULL,
 currency VARCHAR(10) NOT NULL,
 user_id BIGINT NOT NULL REFERENCES users(id)
);
